from __future__ import annotations


FERTILIZER_PRODUCTS = [
    {
        "slug": "ure",
        "name": "Urê",
        "product_type": "Phân đơn",
        "nutrient_profile": "46% N",
        "package_label": "Bao 50 kg",
        "package_size_kg": 50,
        "base_package_price": 590_000,
        "brands": ["Phú Mỹ", "Cà Mau"],
    },
    {
        "slug": "dap",
        "name": "DAP",
        "product_type": "Phân đơn",
        "nutrient_profile": "18-46-0",
        "package_label": "Bao 50 kg",
        "package_size_kg": 50,
        "base_package_price": 1_030_000,
        "brands": ["Đình Vũ", "Nhập khẩu"],
    },
    {
        "slug": "kali-mop",
        "name": "Kali MOP",
        "product_type": "Phân đơn",
        "nutrient_profile": "60% K2O",
        "package_label": "Bao 50 kg",
        "package_size_kg": 50,
        "base_package_price": 760_000,
        "brands": ["Phú Mỹ", "Nhập khẩu"],
    },
    {
        "slug": "kali-sop",
        "name": "Kali SOP",
        "product_type": "Phân đơn",
        "nutrient_profile": "50% K2O + 18% S",
        "package_label": "Bao 50 kg",
        "package_size_kg": 50,
        "base_package_price": 1_050_000,
        "brands": ["Nhập khẩu", "SOP tiêu chuẩn"],
    },
    {
        "slug": "sa",
        "name": "SA",
        "product_type": "Phân đơn",
        "nutrient_profile": "21% N + 24% S",
        "package_label": "Bao 50 kg",
        "package_size_kg": 50,
        "base_package_price": 350_000,
        "brands": ["Nhập khẩu", "Phú Mỹ"],
    },
    {
        "slug": "lan-nung-chay",
        "name": "Lân nung chảy",
        "product_type": "Phân lân",
        "nutrient_profile": "P2O5 + CaO + MgO",
        "package_label": "Bao 50 kg",
        "package_size_kg": 50,
        "base_package_price": 245_000,
        "brands": ["Lâm Thao", "Văn Điển"],
    },
    {
        "slug": "npk-16-16-8",
        "name": "NPK 16-16-8",
        "product_type": "Phân hỗn hợp",
        "nutrient_profile": "16-16-8",
        "package_label": "Bao 50 kg",
        "package_size_kg": 50,
        "base_package_price": 690_000,
        "brands": ["Bình Điền", "Phú Mỹ"],
    },
    {
        "slug": "npk-20-20-15",
        "name": "NPK 20-20-15",
        "product_type": "Phân hỗn hợp",
        "nutrient_profile": "20-20-15",
        "package_label": "Bao 50 kg",
        "package_size_kg": 50,
        "base_package_price": 870_000,
        "brands": ["Bình Điền", "Cà Mau"],
    },
    {
        "slug": "npk-15-15-15",
        "name": "NPK 15-15-15",
        "product_type": "Phân hỗn hợp",
        "nutrient_profile": "15-15-15",
        "package_label": "Bao 50 kg",
        "package_size_kg": 50,
        "base_package_price": 650_000,
        "brands": ["Bình Điền", "Lâm Thao"],
    },
    {
        "slug": "phan-huu-co-vi-sinh",
        "name": "Phân hữu cơ vi sinh",
        "product_type": "Phân hữu cơ",
        "nutrient_profile": "Hữu cơ + vi sinh",
        "package_label": "Bao 25 kg",
        "package_size_kg": 25,
        "base_package_price": 145_000,
        "brands": ["Hữu cơ miền Tây", "Hữu cơ Tây Nguyên"],
    },
]
